production:
  adapter: postgresql
  encoding: unicode
  database: marvel_production
  host: localhost
  pool: 5
  username: pguser
  password: admin

development:
  adapter: postgresql
  encoding: unicode
  database: marvel_development
  host: localhost
  pool: 5
  username: pguser
  password: admin

test:
  adapter: postgresql
  encoding: unicode
  database: marvel_test
  host: localhost
  pool: 5
  username: pguser
  password: admin
