# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 596f4b0e9e5b3f3182f57ef6f52a8de9fcca577b93720e9dfcc39e04a8bc6a4156f1160e5ab862a98623af85074c2bf585da7483ac0f867e99de569b9bc71839

test:
  secret_key_base: b0cc68b0fb955a297d1e34b34b3dcf834eaf4c8cd6cd424ecfa648e90b867b2e8ab569e6749fa294ac8ae54b9d94df91697af39de9e02ca0c6a2f77981a67247

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
